Na_Kabelku/Na_Kabelku/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage),
    path('products/', include('products.urls')),
    path('users/', include('users.urls')),
    path('payments/', include('payments.urls')),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root = settings.MEDIA_ROOT)

Na_Kabelku/products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('', views.products_list, name="list"),
    path('<int:p>/', views.products_list, name="list"),
    path('<str:category>/', views.products_list_category, name="list_category"),
    path('<str:category>/<int:p>/', views.products_list_category, name="list_category"),
    # path('new-post/', views.post_new, name="new-post"),
    path('product/<slug:slug>/', views.product_page, name="page"),
    path('product/<slug:slug>/<int:p>/', views.product_page, name="page"),
    path('product/<slug:slug>/load-reviews/', views.load_reviews, name='load-reviews'),
    path('product/<slug:slug>/load-reviews/<int:p>/', views.load_reviews, name='load-reviews'),
    path('product/reviews/add-review/<int:product_id>/', views.add_review, name='add-review'),
    path('search/list/', views.search_view, name='search_view'),
    path('search/list/<int:p>/', views.search_view, name='search_view'),
]

Na_Kabelku/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register_view, name="register"),
    path('login/', views.login_view, name="login"),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('password/forgot/activate/<uidb64>/<token>/', views.forgot_activate, name='forgot-activate'),
    path('activation/link/<int:user_id>/', views.activate_link, name="activate-link"),
    path('password/forgot/activation/link/<int:user_id>/', views.forgot_activate_link, name="forgot-activate-link"),
    path('password/forgot/', views.forgot_password_view, name="forgot-password"),
    path('password/new/', views.set_new_password, name="set-password"),
    path('logout/', views.logout_view, name="logout"),
]

Na_Kabelku/products/models.py
from django.db import models
from django.utils.text import slugify
from datetime import timedelta
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=100, null=True)
    slug = models.SlugField(null=True, blank=True)
    banner = models.ImageField(blank=True)

    def __str__(self):
        return self.name
    
    def save(self):
        if not self.id:
            self.slug = slugify(self.name)

        super(Category, self).save()

class Brand(models.Model):
    name = models.CharField(max_length=100, null=True)
    slug = models.SlugField(null=True, blank=True)

    def __str__(self):
        return self.name
    
    def save(self):
        if not self.id:
            self.slug = slugify(self.name)

        super(Brand, self).save()

class Product(models.Model):
    title = models.CharField(max_length=75)
    price = models.DecimalField(max_digits=6, default=0.00, decimal_places=2)
    description = models.TextField(blank=True)
    details = models.TextField(blank=True)
    slug = models.SlugField(null=True, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    banner = models.ImageField(blank=True)
    quantity = models.PositiveIntegerField(default=0)
    sold_quantity = models.PositiveBigIntegerField(default=0)
    discount_percentage = models.DecimalField(max_digits=5, decimal_places=2, default=0.00)
    discounted_price = models.DecimalField(max_digits=6, decimal_places=2, default=0.00)
    is_new = models.BooleanField(default=False)

    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products', default="2")
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, related_name='products', null=True)
    
    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title)

        if self.discount_percentage > 0:
            self.discounted_price = self.price - (self.price * (self.discount_percentage / 100))
        else:
            self.discounted_price = self.price
            
        super(Product, self).save(*args, **kwargs)

    def average_rating(self):
        reviews = self.reviews.all()
        if reviews.exists():
            return round(reviews.aggregate(models.Avg('rating'))['rating__avg'])
        return 0

class ProductImage(models.Model):
    product = models.ForeignKey(Product, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product_images/')
    alt_text = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return f"Image for {self.product.title}"
    
class Review(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='reviews')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.PositiveIntegerField()
    comment = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Dodał(a) {self.user.username} - Ocena: {self.rating}"

'''
class Attachment(DatetimeCreatedMixin, AuthorMixin):
    class AttachmentType(models.TextChoices):
        PHOTO = "Photo", _("Photo")
        VIDEO = "Video", _("Video")

    file = models.ImageField('Attachment', upload_to='attachments/')
    file_type = models.CharField('File type', choices=AttachmentType.choices, max_length=10)

    images = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Model that uses the image field')

    class Meta:
        verbose_name = 'Attachment'
        verbose_name_plural = 'Attachments'

'''

Na_Kabelku/products/forms/ReviewForm.py
from django import forms
from ..models import Review
from django.core.exceptions import ValidationError

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['rating', 'comment']
        widgets = {
            'rating': forms.NumberInput(attrs={'min': 1, 'max': 5}),
            'comment': forms.Textarea(attrs={'placeholder': 'Dodaj swoją opinię tutaj...'}),
        }

        error_messages = {
            'rating': {
                'required': 'Proszę podać ocenę od 1 do 5.',
                'invalid': 'Zaznacz prawidłowo ocenę.',
            },
            'comment': {
                'required': 'Komentarz jest wymagany.',
            },
        }

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super().clean()
        
        if not self.user or not self.user.is_authenticated:
            raise ValidationError("Musisz być zalogowany, aby dodać opinię.")

        return cleaned_data

Na_Kabelku/products/views.py
from django.core.paginator import Paginator
from django.shortcuts import render
from .models import Product, Category, Brand, Review
from products.forms.ReviewForm import ReviewForm
from django.db.models import Count
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Avg
import re

# Create your views here.
def products_list(request, p=1):
    path = request.path
    path_matches = bool(re.match(r'^/products/[a-z]+/.*$', path))
    path_matches_paginator = bool(re.match(r'^/products/[0-9]+/.*$', path))

    if path_matches_paginator:
        path_paginator = '/' + '/'.join(path.strip('/').split('/')[:-1]) + '/'
    else:
        path_paginator = request.path

    categories = Category.objects.all().order_by('name').annotate(product_count=Count('products'))
    brands = Brand.objects.all().order_by('name').annotate(product_count=Count('products'))

    sort_by = request.GET.get('sort_by', '-created_date')
    min_price = float(request.GET.get('min-price', '1.00'))
    max_price = float(request.GET.get('max-price', '9999.00'))
    selected_brands = request.GET.getlist('brand')
    selected_brands = [int(brands) for brands in selected_brands]
    selected_categories = request.GET.getlist('category') 
    selected_categories = [int(cat) for cat in selected_categories]

    product_filter = Product.objects.filter(price__range=(min_price, max_price))
    
    if selected_categories:
        product_filter = product_filter.filter(category__in=selected_categories)

    if selected_brands:
        product_filter = product_filter.filter(brand__in=selected_brands)

    products = product_filter.order_by(sort_by)
    
    paginator = Paginator(products, 2)
    page_number = request.GET.get('page', p)
    page_obj = paginator.page(page_number)

    context = {
        'path_matches' : path_matches,
        'products' : page_obj, 
        'categories' : categories,
        'categories_products' : categories,
        'brands' : brands,
        'selected_categories' : selected_categories,
        'selected_brands' : selected_brands,
        'path_paginator' : path_paginator,
        'stars_range' : range(1,6),
    }

    return render(request, 'products/products_list.html', context)

def products_list_category(request, category, p=1):
    path = request.path
    path_matches = bool(re.match(r'^/products/[a-z]+/.*$', path))
    path_matches_paginator = bool(re.match(r'^/products/[a-z]+/[0-9]+/.*$', path))

    if path_matches_paginator:
        path_paginator = '/' + '/'.join(path.strip('/').split('/')[:-1]) + '/'
    else:
        path_paginator = request.path


    categories = Category.objects.all().order_by('name')
    category_id = Category.objects.get(slug = category).id

    path_category = path.strip('/').split('/')[1]
    brands = Brand.objects.filter(products__category = category_id).order_by('name').annotate(product_count=Count('products'))
    
    sort_by = request.GET.get('sort_by', '-created_date')
    min_price = float(request.GET.get('min-price', '1.00'))
    max_price = float(request.GET.get('max-price', '9999.00'))
    selected_brands = request.GET.getlist('brand')
    selected_brands = [int(brands) for brands in selected_brands]

    product_filter = Product.objects.filter(price__range=(min_price, max_price))
    product_filter = product_filter.filter(category=category_id)

    if selected_brands:
        product_filter = product_filter.filter(brand__in=selected_brands)

    products = product_filter.order_by(sort_by)
    
    paginator = Paginator(products, 2)
    page_number = request.GET.get('page', p)
    page_obj = paginator.page(page_number)

    context = {
        'path_matches' : path_matches,
        'products' : page_obj, 
        'brands' : brands,
        'categories' : categories,
        'categories_products' : categories,
        'selected_brands' : selected_brands,
        'path_paginator' : path_paginator,
        'path_category' : path_category,
        'stars_range' : range(1,6),
    }

    return render(request, 'products/products_list.html', context)

def product_page(request, slug, p=1):
    product = Product.objects.get(slug=slug)
    categories = Category.objects.all().order_by('name')

    related_products = Product.objects.filter(category = product.category).exclude(slug=slug)

    reviews = Review.objects.filter(product = product).order_by('-created_at')
    reviews_count = reviews.count()

    average_rating = reviews.aggregate(Avg('rating'))['rating__avg'] or 0
    average_rating_stars = round(average_rating)
    average_rating = round(average_rating, 1)
    rating_counts = {1: 0, 2: 0, 3: 0, 4: 0, 5: 0}
    for review in reviews:
        rating_counts[review.rating] += 1

    rating_counts_percentage = [
        (rating_counts[star] / reviews_count) * 100 if reviews_count > 0 else 0
        for star in range(1, 6)
    ]

    paginator = Paginator(reviews, 5)
    page_number = request.GET.get('page', p)
    page_obj = paginator.page(page_number)  

    context = {
        'product' : product,
        'categories' : categories,
        'related_products' : related_products,
        'reviews' : page_obj,
        'reviews_count' : reviews_count,
        'average_rating' : average_rating,
        'average_rating_stars' : average_rating_stars,
        'rating_counts': rating_counts,
        'rating_counts_percentage' : rating_counts_percentage,
        'stars_range' : range(1,6),
        'has_next': page_obj.has_next(),
    }
    return render(request, 'products/product_page.html', context)

def load_reviews(request, slug, p=2):
    product = Product.objects.get(slug=slug)
    reviews = Review.objects.filter(product = product).order_by('-created_at')
    paginator = Paginator(reviews, 5)
    page_number = request.GET.get('page', p)
    page_obj = paginator.page(page_number)  
    reviews_count = reviews.count()

    reviews_data = []
    for review in page_obj:
        reviews_data.append({
            'username': review.user.username,
            'comment': review.comment,
            'rating': review.rating,
            'created_at': review.created_at.strftime('%d.%m.%Y')
        })

    context ={
        'reviews_list' : reviews_data,
        'reviews_count' : reviews_count,
        'has_next': page_obj.has_next(),
    }
    
    return JsonResponse(context, safe=False)

def add_review(request, product_id):
    if request.method == 'POST':
        product = Product.objects.get(id=product_id)
        form = ReviewForm(request.POST, user=request.user)
        if form.is_valid():
            review = form.save(commit=False)
            form.add_error("rating", "Dziękujemy za dodanie opinii.")
            review.user = request.user
            review.product = product
            review.save()
            return JsonResponse({
                'success': True,
                'username': review.user.username,
                'rating': review.rating,
                'comment': review.comment,
                'created_at': review.created_at.strftime('%d.%m.%Y')
            })
    return JsonResponse({'success': False, 'errors': form.errors}, status=400)

def search_view(request, p=1):
    path = request.path
    path_matches_query = bool(re.match(r'^/products/search/list/.*$', path))
    path_matches_paginator = bool(re.match(r'^/products/search/list/[0-9]+/.*$', path))

    if path_matches_paginator:
        path_paginator = '/' + '/'.join(path.strip('/').split('/')[:-1]) + '/'
    else:
        path_paginator = request.path

    categories = Category.objects.all().order_by('name').annotate(product_count=Count('products'))
    brands = Brand.objects.all().order_by('name').annotate(product_count=Count('products'))

    category_query_name = request.GET.get('category_query', '')

    category_id = None

    if category_query_name != "all":
        category_id = Category.objects.get(name=category_query_name).id

    sort_by = request.GET.get('sort_by', '-created_date')
    min_price = float(request.GET.get('min-price', '1.00'))
    max_price = float(request.GET.get('max-price', '9999.00'))
    selected_brands = request.GET.getlist('brand')
    selected_brands = [int(brands) for brands in selected_brands]
    selected_categories = request.GET.getlist('category') 
    selected_categories = [int(cat) for cat in selected_categories]

    product_filter = Product.objects.filter(price__range=(min_price, max_price))

    query = ''

    if 'query' in request.GET:
        query = request.GET.get('query', '')
        product_filter = Product.objects.filter(title__icontains=query, price__range=(min_price, max_price))
        if category_id:
            product_filter = product_filter.filter(category=category_id)
    
    if selected_categories:
        product_filter = product_filter.filter(category__in=selected_categories)

    if selected_brands:
        product_filter = product_filter.filter(brand__in=selected_brands)

    products = product_filter.order_by(sort_by)
    categories_products = Category.objects.filter(products__in=product_filter).distinct().order_by('name').annotate(product_count=Count('products'))
    brands = Brand.objects.filter(products__in=product_filter).distinct().order_by('name').annotate(product_count=Count('products'))

    paginator = Paginator(products, 2)
    page_number = request.GET.get('page', p)
    page_obj = paginator.page(page_number)

    context = {
        'path_matches_query' : path_matches_query,
        'products' : page_obj, 
        'categories' : categories, 
        'categories_products' : categories_products, 
        'brands' : brands,
        'selected_categories' : selected_categories,
        'selected_brands' : selected_brands,
        'path_paginator' : path_paginator,
        'query' : query,
        'category_query_name' : category_query_name,
        'stars_range' : range(1,6),
    }

Na_Kabelku/products/templates/products/products_list.html
{% extends 'layout.html' %}

{% block title %}
    Posts
{% endblock %}

{% block content %}

<!-- BREADCRUMB -->
<div id="breadcrumb" class="section">
    <!-- container -->
    <div class="container">
        <!-- row -->
        <div class="row">
            <div class="col-md-12">
                <ul class="breadcrumb-tree">
                    <li><a href="/">Strona Główna</a></li>
                    <li><a href="/products/">Kategorie</a></li>
                    {% if path_matches %}
                        <li class="active">{{path_category}}</li>
                    {% else %}
                        <li class="active">Produkty</li>
                    {% endif %}
                </ul>
            </div>
        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
</div>
<!-- /BREADCRUMB -->

<!-- SECTION -->
<div class="section">
    <!-- container -->
    <div class="container">
        {% if path_matches %}
            <form method="GET" action="{% url 'products:list_category' category=path_category %}" id="filter-form">
        {% elif path_matches_query%}
            <form method="GET" action="{% url 'products:search_view' %}" id="filter-form">
                <input type="hidden" name="query" value="{{query}}"/>
                <input type="hidden" name="category_query" value="{{category_query_name}}"/>
                {% else %}
            <form method="GET" action="{% url 'products:list' %}" id="filter-form">
        {% endif %}
            <!-- row -->
            <div class="row">
                <!-- ASIDE -->
                <div id="aside" class="col-md-3">
                    <!-- aside Widget -->
                    <div class="aside">
                        {% if not path_matches %}
                        <h3 class="aside-title">Kategorie</h3>
                            <div class="checkbox-filter">
                                {% for category in categories_products %}
                                    <div class="input-checkbox">
                                        <input type="checkbox" id="category-{{category.id}}" name="category" value="{{category.id}}"
                                        {% if category.id in selected_categories %} checked {% endif %}>
                                        <label for="category-{{category.id}}">
                                            <span></span>
                                                {{ category.name }}
                                            <small>({{category.product_count}})</small>
                                        </label>
                                    </div>
                                {% endfor %}
                            </div>
                        {% comment %} {% else %}
                            <h3 class="aside-title">{{path_category}}</h3> {% endcomment %}
                        {% endif %}
                    </div>
                    <!-- /aside Widget -->
                            
                    <!-- aside Widget -->
                    <div class="aside">
                        <h3 class="aside-title">Cena</h3>
                        <div class="price-filter">
                            <div id="price-slider"></div>
                            <div class="input-number price-min">
                                <input id="price-min" type="number" name="min-price">
                                <span class="qty-up">+</span>
                                <span class="qty-down">-</span>
                            </div>
                            <span>-</span>
                            <div class="input-number price-max">
                                <input id="price-max" type="number" name="max-price">
                                <span class="qty-up">+</span>
                                <span class="qty-down">-</span>
                            </div>
                        </div>
                    </div>
                    <!-- /aside Widget -->

                    <!-- aside Widget -->
                    <div class="aside">
                        <h3 class="aside-title">Producenci</h3>
                        <div class="checkbox-filter">
                            {% for brand in brands %}
                                <div class="input-checkbox">
                                    <input type="checkbox" id="brand-{{brand.id}}" name="brand" value="{{brand.id}}"
                                    {% if brand.id in selected_brands %} checked {% endif %}>
                                    <label for="brand-{{brand.id}}">
                                        <span></span>
                                            {{brand.name}}
                                        <small>({{brand.product_count}})</small>
                                    </label>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                    <!-- /aside Widget -->
                    <button type="submit" class="save-filter-btn">Zapisz</button>
                </div>
                <!-- /ASIDE -->

                <!-- STORE -->
                <div id="store" class="col-md-9">
                    <!-- store top filter -->
                    <div class="store-filter clearfix">
                        <div class="store-sort">
                            {% comment %} <form method="GET" action="{% url 'products:list' %}"> {% endcomment %}
                            <label>
                                Kolejność:
                                <select class="input-select" name="sort_by" onchange="this.form.submit()">
                                    <option value="-created_date" {% if request.GET.sort_by == "-created_date" %}selected{% endif %}>domyślnie</option>
                                    <option value="title" {% if request.GET.sort_by == "title" %}selected{% endif %}>nazwa</option>
                                    <option value="discounted_price" {% if request.GET.sort_by == "discounted_price" %}selected{% endif %}>cena</option>
                                </select>
                            </label>

                            {% comment %} <label>
                                Show:
                                <select class="input-select">
                                    <option value="0">20</option>
                                    <option value="1">50</option>
                                </select>
                            </label> {% endcomment %}
                        </div>
                        {% comment %} <ul class="store-grid">
                            <li class="active"><i class="fa fa-th"></i></li>
                            <li><a href="#"><i class="fa fa-th-list"></i></a></li>
                        </ul> {% endcomment %}
                    </div>
                    <!-- /store top filter -->

                    <!-- store products -->
                    <div class="row">                    
                        {% for product in products %}
                            <!-- product -->
                            <div class="col-md-4 col-xs-6">
                                <div class="product">
                                    <div class="product-img">
                                        <img src="{{product.banner.url}}" alt="{{product.banner.title}}">
                                        <div class="product-label">
                                            {% if product.discount_percentage > 0.00 %}
                                                <span class="sale">-{{ product.discount_percentage|floatformat:0 }}%</span>
                                            {% endif %}
                                            {% if product.is_new == True %}
                                                <span class="new">NEW</span>
                                            {% endif %}
                                        </div>
                                    </div>
                                    <div class="product-body">
                                        <p class="product-category">{{product.category.name}}</p>
                                        <h3 class="product-name"><a href="{% url 'products:page' slug=product.slug %}">{{product.title}}</a></h3>
                                        {% if product.discount_percentage > 0.00 %}
                                            <h4 class="product-price">{{product.discounted_price}}zł <del class="product-old-price">{{product.price}}zł</del></h4>
                                        {% else %}
                                            <h4 class="product-price">{{product.discounted_price}}zł</h4>
                                        {% endif %}
                                        <div class="product-rating">
                                            {% for star in stars_range %}
                                                {% if forloop.counter <= product.average_rating %}
                                                    <i class="fa fa-star"></i>
                                                {% else %}
                                                    <i class="fa fa-star-o empty"></i>
                                                {% endif %}
                                            {% endfor %}
                                        </div>
                                        {% comment %} <div class="product-btns">
                                            <button class="add-to-wishlist"><i class="fa fa-heart-o"></i><span class="tooltipp">add to wishlist</span></button>
                                            <button class="add-to-compare"><i class="fa fa-exchange"></i><span class="tooltipp">add to compare</span></button>
                                            <button class="quick-view"><i class="fa fa-eye"></i><span class="tooltipp">quick view</span></button>
                                        </div> {% endcomment %}
                                    </div>
                                    <div class="add-to-cart">
                                        <button class="add-to-cart-btn"><i class="fa fa-shopping-cart"></i> add to cart</button>
                                    </div>
                                </div>
                            </div>
                            <!-- /product -->
                        {% endfor %}
                    </div>    
                        
                    {% comment %} Should be every 3 products {% endcomment %}
                    {% comment %} <div class="clearfix visible-sm visible-xs"></div> {% endcomment %}
                

                    <!-- store bottom filter -->
                    <div class="store-filter clearfix">
                        <span class="store-qty"><b>{{ products.start_index }}-{{ products.end_index }}</b> z <b>{{ products.paginator.count }}</b> ofert</span>
                        <ul class="store-pagination">
                            {% if products.paginator.num_pages > 1 %}
                                {% if products.number > 1 %}
                                    {% if request.GET %}
                                        <li><a href="{{path_paginator}}{{ products.previous_page_number }}/?{{request.GET.urlencode}}"><i class="fa fa-angle-left"></i></a></li>
                                    {% else %}
                                        <li><a href="{{path_paginator}}{{ products.previous_page_number }}/"><i class="fa fa-angle-left"></i></a></li>
                                    {% endif %}
                                {% endif %}

                                {% for page in products.paginator.page_range %}
                                    {% if page >= products.number|add:-2 and page <= products.number|add:2 %}
                                        {% if page == products.number %}
                                        <li class="active">{{page}}</li>
                                        {% else %}
                                            {% if request.GET %}
                                                <li><a href="{{path_paginator}}{{ page }}/?{{request.GET.urlencode}}">{{ page }}</a></li>
                                            {% else %}
                                                <li><a href="{{path_paginator}}{{ page }}/">{{ page }}</a></li>
                                            {% endif %}
                                        {% endif %}
                                    {% endif %}
                                {% endfor %}

                                {% if products.number < products.paginator.num_pages %}
                                    {% if request.GET %}
                                        <li><a href="{{path_paginator}}{{ products.next_page_number }}/?{{request.GET.urlencode}}"><i class="fa fa-angle-right"></i></a></li>
                                    {% else %}
                                        <li><a href="{{path_paginator}}{{ products.next_page_number }}/"><i class="fa fa-angle-right"></i></a></li>
                                    {% endif %}
                                {% endif %}
                            {% endif %}
                        </ul>
                    </div>
                    <!-- /store bottom filter -->
                </div>
                <!-- /STORE -->
            </div>
            <!-- /row -->
        </form>
    </div>
    <!-- /container -->
</div>
{% endblock %}