Na_Kabelku/Na_Kabelku/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage),
    path('products/', include('products.urls')),
    path('users/', include('users.urls')),
    path('payments/', include('payments.urls')),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root = settings.MEDIA_ROOT)

Na_Kabelku/payments/urls.py
from django.urls import path
from . import views

app_name = 'payments'

urlpatterns = [
    path('cart/', views.cart_detail, name="cart_detail"),
    path('cart/add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('cart/remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('cart/item/update/<int:product_id>/<int:quantity>/', views.item_quantity_update, name='item_quantity_update'),
    path('order/', views.order, name="order"),
    path('summary/', views.summary, name="summary"),
    path('order/confirm/', views.confirm_order, name="confirm_order"),
]

Na_Kabelku/products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('', views.products_list, name="list"),
    path('<int:p>/', views.products_list, name="list"),
    path('<str:category>/', views.products_list_category, name="list_category"),
    path('<str:category>/<int:p>/', views.products_list_category, name="list_category"),
    # path('new-post/', views.post_new, name="new-post"),
    path('product/<slug:slug>/', views.product_page, name="page"),
    path('product/<slug:slug>/<int:p>/', views.product_page, name="page"),
    path('product/<slug:slug>/load-reviews/', views.load_reviews, name='load-reviews'),
    path('product/<slug:slug>/load-reviews/<int:p>/', views.load_reviews, name='load-reviews'),
    path('product/reviews/add-review/<int:product_id>/', views.add_review, name='add-review'),
    path('search/list/', views.search_view, name='search_view'),
    path('search/list/<int:p>/', views.search_view, name='search_view'),
]

Na_Kabelku/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register_view, name="register"),
    path('login/', views.login_view, name="login"),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('password/forgot/activate/<uidb64>/<token>/', views.forgot_activate, name='forgot-activate'),
    path('activation/link/<int:user_id>/', views.activate_link, name="activate-link"),
    path('password/forgot/activation/link/<int:user_id>/', views.forgot_activate_link, name="forgot-activate-link"),
    path('password/forgot/', views.forgot_password_view, name="forgot-password"),
    path('password/new/', views.set_new_password, name="set-password"),
    path('logout/', views.logout_view, name="logout"),
]

Na_Kabelku/payments/forms/BillingDetailsForm.py
from django import forms

class BillingDetailsForm(forms.Form):
    first_name = forms.CharField(
        max_length=100,
        label="Imię",
        widget=forms.TextInput(attrs={
            'class': 'input first-name',
            'placeholder': 'Imię',
        })
    )
    last_name = forms.CharField(
        max_length=100,
        label="Nazwisko",
        widget=forms.TextInput(attrs={
            'class': 'input last-name',
            'placeholder': 'Nazwisko',
        })
    )
    email = forms.EmailField(
        label="Email",
        widget=forms.EmailInput(attrs={
            'class': 'input',
            'placeholder': 'Email',
        })
    )
    address = forms.CharField(
        max_length=255,
        label="Adres",
        widget=forms.TextInput(attrs={
            'class': 'input',
            'placeholder': 'Adres',
        })
    )
    city = forms.CharField(
        max_length=100,
        label="Miasto",
        widget=forms.TextInput(attrs={
            'class': 'input',
            'placeholder': 'Miasto',
        })
    )
    zip_code = forms.CharField(
        max_length=20,
        label="Kod pocztowy",
        widget=forms.TextInput(attrs={
            'class': 'input',
            'pattern': r'^\d{2}-\d{3}$',
            'title': 'Wprowadź kod pocztowy w formacie 12-345',
            'placeholder': 'Kod pocztowy',
        })
    )
    phone = forms.CharField(
        max_length=9,
        label="Telefon",
        widget=forms.TextInput(attrs={
            'type': 'tel',
            'class': 'input',
            'pattern': '[0-9]{9}',
            'title': 'Wprowadź 9-cyfrowy numer telefonu',
            'placeholder': 'Telefon',
        })
    )
    message = forms.CharField(
        label="Wiadomość do sprzedającego",
        required=False,
        widget=forms.Textarea(attrs={
            'class': 'input',
            'placeholder': 'Napisz wiadomość',
        })
    )
    create_account = forms.BooleanField(
        required=False,
        label="Utwórz konto",
        widget=forms.CheckboxInput(attrs={
            'id': 'create-account'
        })
    )

    SHIPPING_METHODS = {
        'inpost': {'label': 'Paczkomat Inpost', 'price': '12.99'},
        'kurier': {'label': 'Kurier DPD', 'price': '17.99'},
        'pobranie': {'label': 'Kurier za pobraniem', 'price': '19.99'},
    }
    
    shipping_method = forms.ChoiceField(
        label="Metody Dostawy",
        required=True,
        choices=[
            ('inpost', 'Paczkomat Inpost (12.99zł)'),
            ('kurier', 'Kurier DPD (17.99zł)'),
            ('pobranie', 'Kurier za pobraniem (19.99zł)')
        ],
        widget=forms.RadioSelect(attrs={
            'class': 'shipping-method',
            'title': 'Wybierz metodę dostawy',
        }),
        error_messages={'required': 'Wybierz metodę dostawy.'}
    )
    billing_method = forms.ChoiceField(
        label="Metody Płatności",
        required=True,
        choices=[
            ('przelew', 'Przelew online'),
            ('BLIK', 'BLIK'),
            ('pobranie', 'Płatność przy odbiorze')
        ],
        widget=forms.RadioSelect(attrs={
            'class': 'billing-method'
        }),
        error_messages={'required': 'Wybierz metodę płatności.'}
    )

Na_Kabelku/payments/views.py
from decimal import Decimal
from django.http import JsonResponse
from django.shortcuts import render
from django.shortcuts import redirect, get_object_or_404, render
from users.models import ClientProfile
from payments.forms.BillingDetailsForm import BillingDetailsForm
from products.models import Category, Product
from django.db.models import Count
from .models import Cart, CartItem, Order, OrderItem
import json

# Create your views here.
def cart_detail(request):
    categories = Category.objects.all().order_by('name').annotate(product_count=Count('products'))

    cart = Cart(request)

    cart_price = cart.get_cart_price()
    is_anymous = request.user.is_anonymous

    if request.user is not None and not is_anymous:
        cart = CartItem.objects.filter(user=request.user)
        base_fee = 12.99
        cart_price = 0
        for item in cart:
            cart_price += item.total_price 
        
        cart_price = base_fee + float(cart_price)

    context = {
        'categories' : categories,
        'cart' : cart,
        'cart_price' : cart_price,
    }

    return render(request, 'carts/cart_detail.html', context)

def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    is_anymous = request.user.is_anonymous

    if request.user is not None and not is_anymous:
        cart_item_in_database = None

        if CartItem.objects.filter(user=request.user, product__id=product_id):
            cart_item_in_database = CartItem.objects.get(user=request.user, product__id=product_id)

        if cart_item_in_database:
            cart_item_in_database.quantity+=1
            cart_item_in_database.save()
        else:
            cart_item = CartItem(user = request.user, product=product, quantity=1)
            cart_item.save()
    else:
        cart.add(product_id)
        cart.save()

    return redirect('payments:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    is_anymous = request.user.is_anonymous

    if request.user is not None and not is_anymous:
        cart_item_in_database = None

        cart_item_in_database = CartItem.objects.filter(user=request.user, product__id=product_id)
        if cart_item_in_database is not None:
            cart_item_in_database.delete()
    else:
        cart.remove(product_id=product_id)

    return redirect('payments:cart_detail')

def item_quantity_update(request, product_id, quantity):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    is_anymous = request.user.is_anonymous
    item = None

    max_quantity = product.quantity
    if quantity > max_quantity:
        quantity = max_quantity
    elif quantity < 0:
        quantity = 0
    else:
        quantity = quantity

    if request.user is not None and not is_anymous:
        cart_item_in_database = None

        if CartItem.objects.filter(user=request.user, product__id=product_id):
            cart_item_in_database = CartItem.objects.get(user=request.user, product__id=product_id)

        if cart_item_in_database:
            cart_item_in_database.quantity = quantity
            cart_item_in_database.save()
            total_price = cart_item_in_database.total_price

        base_fee = 12.99
        cart_price = 0

        for item in CartItem.objects.filter(user=request.user):
            cart_price += item.total_price

        cart_price = base_fee + float(cart_price)

    else:
        cart.update(product_id, quantity)
        cart.save()
        total_price = cart.get_total_price(product_id)
        cart_price = cart.get_cart_price()
    
    return JsonResponse({'price': total_price, 'cart_price': cart_price})

def order(request):
    categories = Category.objects.all().order_by('name').annotate(product_count=Count('products'))
    cart = Cart(request)

    cart_price = cart.get_cart_price()
    is_anymous = request.user.is_anonymous

    if request.method == 'POST':
        form = BillingDetailsForm(request.POST)
        if form.is_valid():
            return redirect("payments:summary")
    else:
        form = BillingDetailsForm()

        if request.user is not None and not is_anymous:
            cart = CartItem.objects.filter(user=request.user)
            cart_price = 0
            base_fee = 12.99
            for item in cart:
                cart_price += item.total_price 
            
            cart_price = base_fee + float(cart_price)
            user = request.user
            user_id = user.id

            try:
                user_profile = ClientProfile.objects.get(user_id=user_id)
            except:
                raise Exception("Podany użytkownik nie istnieje")
            
            form = BillingDetailsForm(initial={
                'first_name': user.first_name,
                'last_name': user.last_name,
                'email': user.email,
                'address': user_profile.address,
                'city': user_profile.city,
                'zip_code': user_profile.zip_code,
                'phone': user_profile.phone,
            })

    context = {
        'categories' : categories,
        'cart' : cart,
        'cart_price' : cart_price,
        'form' : form,
    }

    return render(request, 'carts/order.html', context)

def summary(request):
    categories = Category.objects.all().order_by('name').annotate(product_count=Count('products'))

    form = request.POST

    items=[]

    for key, value in form.items():
        if key.startswith('item-'):
            item_id = key.split('-')[1]
            count = value.split('-')[1]
            item = Product.objects.filter(id=item_id)

            price = 0.0
            for product in item:
                price = product.price * int(count)
                
            items.append({'item': item, 'count': count, 'price': price})

    context = {
        'categories' : categories,
        'form' : form,
        'items': items,
    }

    return render(request, 'carts/summary.html', context)

def confirm_order(request):
    form = request.POST
    print(form)
    user = request.user if request.user.is_authenticated else None

    order = Order.objects.create(
        user = user,

        guest_first_name = form.get('first_name'),
        guest_last_name = form.get('last_name'),
        guest_email = form.get('email'),
        guest_address = form.get('address'),
        guest_city = form.get('city'),
        guest_zip_code = form.get('zip_code'),
        guest_phone = form.get('phone'),
        guest_message = form.get('message'),

        billing_method = form.get('billing_method'),
        shipping_method = form.get('shipping_method'),

        status = 'ORDERED',

        total_amount = form.get('total_price')
    )

    for key in form:
        if key.startswith('item-'):
            item_id = key.split('-')[1]
            item_count = request.POST.get(key)
            product_obj = get_object_or_404(Product, id=item_id)
            product_price = product_obj.price * Decimal(item_count)
            ordered_item = OrderItem.objects.create(
                product = product_obj, 
                quantity = item_count, 
                price = product_price
            )
            order.order_items.add(ordered_item)

    order.save()

    # items=[]

    # for key, value in form.items():
    #     if key.startswith('item-'):
    #         item_id = key.split('-')[1]
    #         count = value.split('-')[1]
    #         item = Product.objects.filter(id=item_id)

    #         price = 0.0
    #         for product in item:
    #             price = product.price * int(count)
                
    #         items.append({'item': item, 'count': count, 'price': price})

    context = {
        'form' : form,
        # 'items': items,
    }

    return render(request, 'carts/summary.html', context)

Na_Kabelku/payments/templates/carts/cart_detail.html
{% extends 'layout.html' %}

{% block content %}
	<!-- BREADCRUMB -->
	<div id="breadcrumb" class="section">
		<!-- container -->
		<div class="container">
			<!-- row -->
			<div class="row">
				<div class="col-md-12">
					<h3 class="breadcrumb-header">Twój Koszyk</h3>
				</div>
			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</div>
	<!-- /BREADCRUMB -->

	<!-- SECTION -->
	<div class="section">
		<!-- container -->
		<div class="container">
			<!-- row -->
			<div class="row">

				<div class="col-md-8 row">
					<!-- cart Details -->
					<div class="cart-details">
						{% for item in cart %}
							{% comment %} <li>{{details.quantity}}</li> {% endcomment %}
							<div id="cart-item-{{ item.product.id }}">
								<div class="cart-img">
									<img src="{{item.product.banner.url}}" />
								</div>
								<h5><a href="{% url 'products:page' slug=item.product.slug %}">{{ item.product.title }}</a></h5>
								<div class="cart-quantity">
									<div class="qty-label">
										<div class="input-number">
											<span class="qty-down">-</span>
											<input type="number" id="item-quantity-{{ item.product.id }}" value="{{item.quantity}}" min="0" max="{{item.product.quantity}}">
											<span class="qty-up">+</span>
										</div>
									</div>
									<div class="price-label">
										<h3 class="product-price">{{item.total_price}}zł</h3>
										<h4 class="remove-product"><a href="{% url 'payments:cart_remove' item.product.id %}">&#10060</a></h4>
									</div>
									{% comment %} <p> - Quantity: {{ item.quantity }}
									- Total: ${{ item.total_price }}</p> {% endcomment %}
								</div>
								{% comment %} <a href="{% url 'payments:cart_remove' item.product.id %}">Remove</a> {% endcomment %}
							</div>
						{% endfor %}
					</div>
					<!-- /cart Details -->
				</div>

				<!-- Order Details -->
				<div class="col-md-4 order-details">
					<div class="section-title text-center">
						<h3 class="title">Twoje zamówienie</h3>
					</div>
					<div class="order-summary">
						<div class="order-col">
							<div><strong>PRODUKT</strong></div>
							<div><strong>CENA</strong></div>
						</div>
						<div class="order-products">
							{% for item in cart %}
								<div class="order-col" id="order-item-{{item.product.id}}">
									<div>{{item.quantity}}x	{{item.product.title}}</div>
									<div>{{item.total_price}}zł</div>
								</div>
							{% endfor %}
						</div>
						<div class="order-col">
							<div><strong>Dostawa od</strong></div>
							<div><strong>12.99zł</strong></div>
						</div>
						<div class="order-col">
							<div><strong>RAZEM</strong></div>
							<div><strong class="order-total">{{cart_price}}zł</strong></div>
						</div>
					</div>
					
					<a href="/payments/order" class="primary-btn order-submit">Dostawa i płatność</a>
				</div>
				<!-- /Order Details -->
			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</div>
	<!-- /SECTION -->
{% endblock %}

Na_Kabelku/payments/templates/carts/summary.html
{% extends 'layout.html' %}

{% block content %}
	<!-- BREADCRUMB -->
	<div id="breadcrumb" class="section">
		<!-- container -->
		<div class="container">
			<!-- row -->
			<div class="row">
				<div class="col-md-12">
					<h3 class="breadcrumb-header">Podsumowanie</h3>
				</div>
			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</div>
	<!-- /BREADCRUMB -->

	<!-- SECTION -->
    <div class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">
                <div class="col-md-1">
                </div>
                <div class="col-md-8">
                    <!-- Billing Details -->
                    <div class="billing-details">
                        <div class="section-title">
                            <h3 class="title">Dane odbiorcy</h3>
                        </div>
                        <div class="form-group name">
                            <div class="first-container">
                                <label for="first-name" class="form-label">Imię</label><br>
                                {{form.first_name}}
                            </div>
                            <div class="last-container">
                                <label for="last-name" class="form-label">Nazwisko</label><br>
                                {{form.last_name}}
                            </div>
                        </div>
                        <div class="form-group email">
                            <label for="email" class="form-label">Email</label><br>
                            {{form.email}}
                        </div>
                        <div class="form-group address">
                            <label for="address" class="form-label">Adres</label><br>
                            {{form.address}}
                        </div>
                        <div class="form-group">
                            <div class="first-container">
                                <label for="city" class="form-label">Miasto</label><br>
                                {{form.city}}
                            </div>
                            <div class="last-container">
                                <label for="zip-code" class="form-label">Kod pocztowy</label><br>
                                {{form.zip_code}}
                            </div>
                        </div>
                        <div class="form-group phone">
                            <label for="tel" class="form-label">Telefon</label><br>
                            {{form.phone}}
                        </div>

                        <!-- Order notes -->
                        <div class="order-notes">
                            <label for="tel" class="form-label">Wiadomość do sprzedającego</label><br>
                            {{form.message}}
                        </div><br>
                        <!-- /Order notes -->

                        <div class="form-group">
                            <label class="form-label">Zamówione produkty</label><br>
                        <!--Products-->
                        {% for order_item in items %}
                            {% comment %} <li>{{details.quantity}}</li> {% endcomment %}
                            {% for product in order_item.item %}
                                <div class="order-item">
                                    <div class="item-img">
                                        <img src="{{product.banner.url}}"/>
                                    </div>
                                    <h6>{{product.title}} ({{order_item.count}}x) - {{order_item.price}}zł</h6>
                                    {% comment %} <a href="{% url 'payments:cart_remove' item.product.id %}">Remove</a> {% endcomment %}
                                </div>
                            {% endfor %}
                        {% endfor %}
                        <!--/Products-->
                        </div>

                        <div class="form-group">
                            <label>Metoda Dostawy</label><br>
                            {% if form.shipping_method == 'pobranie' %}
                                Kurier za pobraniem (19.99zł)
                            {% elif form.shipping_method == 'kurier' %}
                                Kurier DPD (17.99zł)
                            {% elif form.shipping_method == 'inpost' %}
                                Paczkomat Inpost (12.99zł)
                            {% else %}
                                -
                            {% endif %}
                        </div>

                        <div class="form-group">
                            <label>Metoda Płatności</label><br>
                            {% if form.billing_method == 'pobranie' %}
                                Płatność przy odbiorze
                            {% elif form.billing_method == 'przelew'%}
                                Przelew online
                            {% else %}
                                {{ form.billing_method }}
                            {% endif %}
                        </div>

                        <div class="form-group mt-5">
                            <br>
                            <h4>Do zapłaty: {{form.total_price}}zł</h4>
                        </div>
                    </div>

                    <form id="orderForm" action="/payments/order/confirm/" method="POST">
                        <div id="confirm-form-hidden">

                            <!-- CSRF Token (for Django security) -->
                            <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
                    
                            <label for="first_name">Imię:</label>
                            <input type="text" name="first_name" value="{{form.first_name}}" required><br><br>
                    
                            <label for="last_name">Nazwisko:</label>
                            <input type="text" name="last_name" value="{{form.last_name}}" required><br><br>
                    
                            <label for="email">Email:</label>
                            <input type="email" name="email" value="{{form.email}}" required><br><br>
                    
                            <label for="address">Adres:</label>
                            <input type="text" name="address" value="{{form.address}}" required><br><br>
                    
                            <label for="city">Miasto:</label>
                            <input type="text" name="city" value="{{form.city}}" required><br><br>
                    
                            <label for="zip_code">Kod pocztowy:</label>
                            <input type="text" name="zip_code" value="{{form.zip_code}}" required><br><br>
                    
                            <label for="phone">Telefon:</label>
                            <input type="tel" name="phone" value="{{form.phone}}" required><br><br>
                    
                            <label for="message">Wiadomość do sprzedającego:</label>
                            <textarea name="message">{{form.message}}</textarea><br><br>
                    
                            <label for="shipping_method">Metoda Dostawy:</label>
                            <select name="shipping_method">
                                {%if form.shipping_method == "kurier"%}
                                    <option value="kurier" selected>Kurier DPD</option>
                                {%elif form.shipping_method == "pobranie"%}    
                                    <option value="pobranie" selected>Kurier za pobraniem</option>
                                {%elif form.shipping_method == "inpost"%}
                                    <option value="inpost" selected>Paczkomat Inpost</option>
                                {%else%}
                                    -
                                {%endif%}
                            </select><br><br>
                    
                            <label for="billing_method">Metoda Płatności:</label>
                            <select name="billing_method">
                                {%if form.billing_method == "BLIK"%}
                                    <option value="BLIK" selected>BLIK</option>
                                {%elif form.billing_method == "przelew"%}    
                                    <option value="przelew" selected>Przelew online</option>
                                {%elif form.billing_method == "pobranie"%}
                                    <option value="pobranie" selected>Płatność przy odbiorze</option>
                                {%else%}
                                    -
                                {%endif%}
                            </select><br><br>
                    
                            <h3>Zamówione Produkty:</h3>
                            {% for order_item in items %}
                                {% comment %} <li>{{details.quantity}}</li> {% endcomment %}
                                {% for product in order_item.item %}
                                    <input type="number" name="item-{{product.id}}" value="{{order_item.count}}" min="1">
                                {% endfor %}
                            {% endfor %}
                    
                            <input type="hidden" name="total_price" value="{{form.total_price}}">
                        </div>

                        <div class="row">
                            <button class="primary-btn confirm_btn" id="confirm_btn">Zatwierdź</button>
                        </div>
                    </form>
                    
                </div>
                <div class="col-md-3">
                </div>
            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /SECTION -->
{% endblock %}