Na_Kabelku/Na_Kabelku/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage),
    path('products/', include('products.urls')),
    path('users/', include('users.urls')),
    path('payments/', include('payments.urls')),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root = settings.MEDIA_ROOT)

Na_Kabelku/products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('', views.products_list, name="list"),
    path('<int:p>/', views.products_list, name="list"),
    path('<str:category>/', views.products_list_category, name="list_category"),
    path('<str:category>/<int:p>/', views.products_list_category, name="list_category"),
    # path('new-post/', views.post_new, name="new-post"),
    path('product/<slug:slug>/', views.product_page, name="page"),
    path('product/<slug:slug>/<int:p>/', views.product_page, name="page"),
    path('product/<slug:slug>/load-reviews/', views.load_reviews, name='load-reviews'),
    path('product/<slug:slug>/load-reviews/<int:p>/', views.load_reviews, name='load-reviews'),
    path('product/reviews/add-review/<int:product_id>/', views.add_review, name='add-review'),
    path('search/list/', views.search_view, name='search_view'),
    path('search/list/<int:p>/', views.search_view, name='search_view'),
]

Na_Kabelku/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register_view, name="register"),
    path('login/', views.login_view, name="login"),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('password/forgot/activate/<uidb64>/<token>/', views.forgot_activate, name='forgot-activate'),
    path('activation/link/<int:user_id>/', views.activate_link, name="activate-link"),
    path('password/forgot/activation/link/<int:user_id>/', views.forgot_activate_link, name="forgot-activate-link"),
    path('password/forgot/', views.forgot_password_view, name="forgot-password"),
    path('password/new/', views.set_new_password, name="set-password"),
    path('logout/', views.logout_view, name="logout"),
]

Na_Kabelku/templates/home.html
{% extends 'layout.html' %}

{% block content %}
	<!-- SECTION -->
	<div class="section">
		<!-- container -->
		<div class="container">
			<!-- row -->
			<div class="row">
				{% for category in categories_home %}
				<!-- shop -->
				<div class="col-md-4 col-xs-6">
					<div class="shop">
						<div class="shop-img">
							<img src="{{category.banner.url}}" alt="{{category.name}}">
						</div>
						<div class="shop-body">
							<h3>{{category.name}}</h3>
							<a href="{% url 'products:list_category' category=category.slug %}" class="cta-btn">Przeglądaj <i class="fa fa-arrow-circle-right"></i></a>
						</div>
					</div>
				</div>
				<!-- /shop -->
				{% endfor %}
			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</div>
	<!-- /SECTION -->
	<input type="hidden" id="price-max">
	<input type="hidden" id="price-min">
	<!-- SECTION -->
	<div class="section">
		<!-- container -->
		<div class="container">
			<!-- row -->
			<div class="row">

				<!-- section title -->
				<div class="col-md-12">
					<div class="section-title">
						<h3 class="title">Nowe oferty</h3>
					</div>
				</div>
				<!-- /section title -->

				<!-- Products tab & slick -->
				<div class="col-md-12">
					<div class="row">
						<div class="products-tabs">
							<!-- tab -->
							<div id="tab1" class="tab-pane active">
								<div class="products-slick" data-nav="#slick-nav-1">
									{% for product in new_products %}
									<!-- product -->
									<div class="product">
										<div class="product-img">
											<img src="{{product.banner.url}}" alt="{{product.name}}">
											<div class="product-label">
												{% if product.discount_percentage > 0.00 %}
													<span class="sale">-{{product.discount_percentage|floatformat:0}}%</span>
												{% endif %}
												{% if product.is_new == True %}
													<span class="new">New</span>
												{% endif %}
											</div>
										</div>
										<div class="product-body">
											<p class="product-category">{{product.category.name}}</p>
											<h3 class="product-name"><a href="/products/product/{{product.slug}}">{{product.title}}</a></h3>
											{% if product.discount_percentage > 0.00 %}
                                            	<h4 class="product-price">{{product.discounted_price}}zł <del class="product-old-price">{{product.price}}zł</del></h4>
											{% else %}
												<h4 class="product-price">{{product.discounted_price}}zł</h4>
											{% endif %}
											{% comment %} <div class="product-rating">
												<i class="fa fa-star"></i>
												<i class="fa fa-star"></i>
												<i class="fa fa-star"></i>
												<i class="fa fa-star"></i>
												<i class="fa fa-star"></i>
											</div>
											<div class="product-btns">
												<button class="add-to-wishlist"><i class="fa fa-heart-o"></i><span class="tooltipp">add to wishlist</span></button>
												<button class="add-to-compare"><i class="fa fa-exchange"></i><span class="tooltipp">add to compare</span></button>
												<button class="quick-view"><i class="fa fa-eye"></i><span class="tooltipp">quick view</span></button>
											</div> {% endcomment %}
											<div>
												<p>Dodano: {{product.created_date|date:"d.m.Y"}}</p>
											</div>
										</div>
										<div class="add-to-cart">
											<button class="add-to-cart-btn"><i class="fa fa-shopping-cart"></i> dodaj do koszyka</button>
										</div>
									</div>
									<!-- /product -->
									{% endfor %}
								</div>
								<div id="slick-nav-1" class="products-slick-nav"></div>
							</div>
							<!-- /tab -->
						</div>
					</div>
				</div>
				<!-- Products tab & slick -->
			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</div>
	<!-- /SECTION -->

	<!-- HOT DEAL SECTION -->
	<div id="hot-deal" class="section">
		<!-- container -->
		<div class="container">
			<!-- row -->
			<div class="row">
				<div class="col-md-12">
					<div class="hot-deal">
						<ul class="hot-deal-countdown">
							<li>
								<div>
									<h3 id="days"></h3>
									<span>Dni</span>
								</div>
							</li>
							<li>
								<div>
									<h3 id="hours"></h3>
									<span>Godzin</span>
								</div>
							</li>
							<li>
								<div>
									<h3 id="minutes">34</h3>
									<span>Minut</span>
								</div>
							</li>
							<li>
								<div>
									<h3 id="seconds">60</h3>
									<span>Sekund</span>
								</div>
							</li>
						</ul>
						<h2 class="text-uppercase">nowe produkty nadchodzą</h2>
						<p>promocje nawet do 50%</p>
						<a class="primary-btn cta-btn" href="/products/">Zobacz oferty</a>
					</div>
				</div>
			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</div>
	<!-- /HOT DEAL SECTION -->

	<!-- SECTION -->
	<div class="section">
		<!-- container -->
		<div class="container">
			<!-- row -->
			<div class="row">

				<!-- section title -->
				<div class="col-md-12">
					<div class="section-title">
						<h3 class="title">najlepsze oferty</h3>
					</div>
				</div>
				<!-- /section title -->

				<!-- Products tab & slick -->
				<div class="col-md-12">
					<div class="row">
						<div class="products-tabs">
							<!-- tab -->
							<div id="tab2" class="tab-pane fade in active">
								<div class="products-slick" data-nav="#slick-nav-2">
									{% for product in top_products %}
									<!-- product -->
									<div class="product">
										<div class="product-img">
											<img src="{{product.banner.url}}" alt="{{product.name}}">
											<div class="product-label">
												{% if product.discount_percentage > 0.00 %}
													<span class="sale">-{{product.discount_percentage|floatformat:0}}%</span>
												{% endif %}
												{% if product.is_new == True %}
													<span class="new">New</span>
												{% endif %}
											</div>
										</div>
										<div class="product-body">
											<p class="product-category">{{product.category.name}}</p>
											<h3 class="product-name"><a href="/products/product/{{product.slug}}">{{product.title}}</a></h3>
											{% if product.discount_percentage > 0.00 %}
                                            	<h4 class="product-price">{{product.discounted_price}}zł <del class="product-old-price">{{product.price}}zł</del></h4>
											{% else %}
												<h4 class="product-price">{{product.discounted_price}}zł</h4>
											{% endif %}
											{% comment %} <div class="product-rating">
												<i class="fa fa-star"></i>
												<i class="fa fa-star"></i>
												<i class="fa fa-star"></i>
												<i class="fa fa-star"></i>
												<i class="fa fa-star"></i>
											</div> {% endcomment %}
											{% comment %} <div class="product-btns">
												<button class="add-to-wishlist"><i class="fa fa-heart-o"></i><span class="tooltipp">add to wishlist</span></button>
												<button class="add-to-compare"><i class="fa fa-exchange"></i><span class="tooltipp">add to compare</span></button>
												<button class="quick-view"><i class="fa fa-eye"></i><span class="tooltipp">quick view</span></button>
											</div> {% endcomment %}
											<div>
												<p>Kupiło {{product.sold_quantity}} osób</p>
											</div>
										</div>
										<div class="add-to-cart">
											<button class="add-to-cart-btn"><i class="fa fa-shopping-cart"></i> dodaj do koszyka</button>
										</div>
									</div>
									<!-- /product -->
									{% endfor %}
								</div>
								<div id="slick-nav-2" class="products-slick-nav"></div>
							</div>
							<!-- /tab -->
						</div>
					</div>
				</div>
				<!-- /Products tab & slick -->
			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</div>
	<!-- /SECTION -->

	<!-- SECTION -->
	<div class="section">
		<!-- container -->
		<div class="container">
			<!-- row -->
			<div class="row">
				{% for category, products in top_products_category.items %}
					<div class="col-md-4 col-xs-6">
						<div class="section-title">
							<h4 class="title">{{category.name}}</h4>
							<div class="section-nav">
								<div id="slick-nav-category-{{category.id}}" class="products-slick-nav"></div>
							</div>
						</div>
						<div class="products-widget-slick" data-nav="#slick-nav-category-{{category.id}}">
							<div>
							{% for product in products %}
								
								<!-- product widget -->
								<div class="product-widget">
									<div class="product-img">
										<img src="{{product.banner.url}}" alt="{{product.name}}">
									</div>
									<div class="product-body">
										<h3 class="product-name"><a href="/products/{{product.slug}}">{{product.title}}</a></h3>
										<h4 class="product-price">{{product.discounted_price}}zł <del class="product-old-price">{{product.price}}</del></h4>
										<p class="product-category">Kupiło {{product.sold_quantity}} osób</p>
									</div>
								</div>
								<!-- /product widget -->

								{% if forloop.counter == 3 %}
									</div>
									<div>
								{% endif %}
							{% endfor %}
							</div>
						</div>
					</div>

					{% if forloop.counter|divisibleby:2 %}
						<div class="clearfix visible-sm visible-xs"></div>
					{% endif %}

				{% endfor %}

			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</div>
	<!-- /SECTION -->
{% endblock %}

Na_Kabelku/templates/layout.html
<!DOCTYPE html>
<html lang="pl">
    {% load static %}
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<title>
            {% block title %}
                NaKabelku
            {% endblock%}
        </title>

		<!--Icon-->
		<link rel="icon" href="\..\static\img\logo.jpg"/>

 		<!-- Google font -->
 		<link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700" rel="stylesheet">

 		<!-- Bootstrap -->
 		<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>

 		<!-- Slick -->
 		<link type="text/css" rel="stylesheet" href="{% static 'css/slick.css' %}"/>
 		<link type="text/css" rel="stylesheet" href="{% static 'css/slick-theme.css' %}"/>

 		<!-- nouislider -->
 		<link type="text/css" rel="stylesheet" href="{% static 'css/nouislider.min.css' %}"/>

 		<!-- Font Awesome Icon -->
 		<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">

 		<!-- Custom stlylesheet -->
 		<link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}"/>

    </head>
	<body>
		<!-- HEADER -->
		<header>
			<!-- TOP HEADER -->
			<div id="top-header">
				<div class="container">
					<ul class="header-links pull-left">
						<li><a href="#"><i class="fa fa-phone"></i> +021-95-51-84</a></li>
						<li><a href="#"><i class="fa fa-envelope-o"></i> email@email.com</a></li>
						<li><a href="#"><i class="fa fa-map-marker"></i> 1734 Stonecoal Road</a></li>
					</ul>
					<ul class="header-links pull-right">
						<li><a href="{% url 'users:register' %}"><i class="fa fa-dollar"></i> USD</a></li>
						<li><a href="{% url 'users:login' %}"><i class="fa fa-user-o"></i> My Account</a></li>
					</ul>
				</div>
			</div>
			<!-- /TOP HEADER -->

			<!-- MAIN HEADER -->
			<div id="header">
				<!-- container -->
				<div class="container">
					<!-- row -->
					<div class="row">
						<!-- LOGO -->
						<div class="col-md-3">
							<div class="header-logo">
								<a href="/" class="logo">
									{% comment %} <img src="\..\static\img\logo.jpg" alt="NaKabelku" class="col-md-6 margin-right"> {% endcomment %}
								</a>
							</div>
						</div>
						<!-- /LOGO -->

						<!-- SEARCH BAR -->
						<div class="col-md-6">
							<div class="header-search">
								<form method="get" action="{% url 'products:search_view' %}">
									<select class="input-select" name="category_query">
										<option value="all">Wszystko</option>
										{% for category in categories %}
											{% if category_query_name == category.name %}
												<option value="{{category.name}}" selected>{{category.name}}</option>
											{% else %}
												<option value="{{category.name}}">{{category.name}}</option>
											{% endif %}
										{% endfor %}
									</select>
									{% if query %}
										<input class="input" id="search-input" name="query" placeholder="Czego szukasz" value="{{query}}">
									{% else %}
										<input class="input" id="search-input" name="query" placeholder="Czego szukasz">
									{% endif %}
									<button class="search-btn" id="search-btn">Szukaj</button>
								</form>
							</div>
						</div>
						<!-- /SEARCH BAR -->

						<!-- ACCOUNT -->
						<div class="col-md-3 clearfix">
							<div class="header-ctn">
								<!-- Wishlist -->
								<div>
									<a href="#">
										<i class="fa fa-heart-o"></i>
										<span>Your Wishlist</span>
										<div class="qty">2</div>
									</a>
								</div>
								<!-- /Wishlist -->

								<!-- Cart -->
								<div class="dropdown">
									<a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
										<i class="fa fa-shopping-cart"></i>
										<span>Your Cart</span>
										<div class="qty">3</div>
									</a>
									<div class="cart-dropdown">
										<div class="cart-list">
											<div class="product-widget">
												<div class="product-img">
													<img src="./img/product01.png" alt="">
												</div>
												<div class="product-body">
													<h3 class="product-name"><a href="#">product name goes here</a></h3>
													<h4 class="product-price"><span class="qty">1x</span>$980.00</h4>
												</div>
												<button class="delete"><i class="fa fa-close"></i></button>
											</div>

											<div class="product-widget">
												<div class="product-img">
													<img src="./img/product02.png" alt="">
												</div>
												<div class="product-body">
													<h3 class="product-name"><a href="#">product name goes here</a></h3>
													<h4 class="product-price"><span class="qty">3x</span>$980.00</h4>
												</div>
												<button class="delete"><i class="fa fa-close"></i></button>
											</div>
										</div>
										<div class="cart-summary">
											<small>3 Item(s) selected</small>
											<h5>SUBTOTAL: $2940.00</h5>
										</div>
										<div class="cart-btns">
											<a href="#">View Cart</a>
											<a href="#">Checkout  <i class="fa fa-arrow-circle-right"></i></a>
										</div>
									</div>
								</div>
								<!-- /Cart -->

								<!-- Menu Toogle -->
								<div class="menu-toggle">
									<a href="#">
										<i class="fa fa-bars"></i>
										<span>Menu</span>
									</a>
								</div>
								<!-- /Menu Toogle -->
							</div>
						</div>
						<!-- /ACCOUNT -->
					</div>
					<!-- row -->
				</div>
				<!-- container -->
			</div>
			<!-- /MAIN HEADER -->
		</header>
		<!-- /HEADER -->

		<!-- NAVIGATION -->
		<nav id="navigation">
			<!-- container -->
			<div class="container">
				<!-- responsive-nav -->
				<div id="responsive-nav">
					<!-- NAV -->
					<ul class="main-nav nav navbar-nav">
						{% if request.path == "/"%}
							<li class="active"><a href="/">Strona Główna</a></li>
							<li><a href="{% url 'products:list' %}">Produkty</a></li>
						{% elif request.path == '/products/' %}
							<li><a href="/">Strona Główna</a></li>
							<li class="active"><a href="{% url 'products:list' %}">Produkty</a></li>
						{% else %}
							<li><a href="/">Strona Główna</a></li>
							<li><a href="{% url 'products:list' %}">Produkty</a></li>
						{% endif %}

						{% for category in categories %}
							{% if category.slug in request.path %}
								<li class="active">
									<a href="{% url 'products:list_category' category=category.slug %}">{{ category.name }}</a>
								</li>
							{% else %}
								<li>
									<a href="{% url 'products:list_category' category=category.slug %}">{{ category.name }}</a>
								</li>
							{% endif %}
						{% endfor %}
					</ul>
					<!-- /NAV -->
				</div>
				<!-- /responsive-nav -->
			</div>
			<!-- /container -->
		</nav>
		<!-- /NAVIGATION -->

        {% block content %}
        {% endblock%}

		<!-- NEWSLETTER -->
		<div id="newsletter" class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<div class="col-md-12">
						<div class="newsletter">
							<p>Sign Up for the <strong>NEWSLETTER</strong></p>
							<form>
								<input class="input" type="email" placeholder="Enter Your Email">
								<button class="newsletter-btn"><i class="fa fa-envelope"></i> Subscribe</button>
							</form>
							<ul class="newsletter-follow">
								<li>
									<a href="#"><i class="fa fa-facebook"></i></a>
								</li>
								<li>
									<a href="#"><i class="fa fa-twitter"></i></a>
								</li>
								<li>
									<a href="#"><i class="fa fa-instagram"></i></a>
								</li>
								<li>
									<a href="#"><i class="fa fa-pinterest"></i></a>
								</li>
							</ul>
						</div>
					</div>
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /NEWSLETTER -->

		<!-- FOOTER -->
		<footer id="footer">
			<!-- top footer -->
			<div class="section">
				<!-- container -->
				<div class="container">
					<!-- row -->
					<div class="row">
						<div class="col-md-3 col-xs-6">
							<div class="footer">
								<h3 class="footer-title">About Us</h3>
								<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut.</p>
								<ul class="footer-links">
									<li><a href="#"><i class="fa fa-map-marker"></i>1734 Stonecoal Road</a></li>
									<li><a href="#"><i class="fa fa-phone"></i>+021-95-51-84</a></li>
									<li><a href="#"><i class="fa fa-envelope-o"></i>email@email.com</a></li>
								</ul>
							</div>
						</div>

						<div class="col-md-3 col-xs-6">
							<div class="footer">
								<h3 class="footer-title">Categories</h3>
								<ul class="footer-links">
									<li><a href="#">Hot deals</a></li>
									<li><a href="#">Laptops</a></li>
									<li><a href="#">Smartphones</a></li>
									<li><a href="#">Cameras</a></li>
									<li><a href="#">Accessories</a></li>
								</ul>
							</div>
						</div>

						<div class="clearfix visible-xs"></div>

						<div class="col-md-3 col-xs-6">
							<div class="footer">
								<h3 class="footer-title">Information</h3>
								<ul class="footer-links">
									<li><a href="#">About Us</a></li>
									<li><a href="#">Contact Us</a></li>
									<li><a href="#">Privacy Policy</a></li>
									<li><a href="#">Orders and Returns</a></li>
									<li><a href="#">Terms & Conditions</a></li>
								</ul>
							</div>
						</div>

						<div class="col-md-3 col-xs-6">
							<div class="footer">
								<h3 class="footer-title">Service</h3>
								<ul class="footer-links">
									<li><a href="#">My Account</a></li>
									<li><a href="#">View Cart</a></li>
									<li><a href="#">Wishlist</a></li>
									<li><a href="#">Track My Order</a></li>
									<li><a href="#">Help</a></li>
								</ul>
							</div>
						</div>
					</div>
					<!-- /row -->
				</div>
				<!-- /container -->
			</div>
			<!-- /top footer -->

			<!-- bottom footer -->
			<div id="bottom-footer" class="section">
				<div class="container">
					<!-- row -->
					<div class="row">
						<div class="col-md-12 text-center">
							<ul class="footer-payments">
								<li><a href="#"><i class="fa fa-cc-visa"></i></a></li>
								<li><a href="#"><i class="fa fa-credit-card"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-paypal"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-mastercard"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-discover"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-amex"></i></a></li>
							</ul>
							<span class="copyright">
								<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
								Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
							<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
							</span>


						</div>
					</div>
						<!-- /row -->
				</div>
				<!-- /container -->
			</div>
			<!-- /bottom footer -->
		</footer>
		<!-- /FOOTER -->

		<!-- jQuery Plugins -->
		<script src="{% static 'js/jquery.min.js' %}"></script>
		<script src="{% static 'js/bootstrap.min.js' %}"></script>
		<script src="{% static 'js/slick.min.js' %}"></script>
		<script src="{% static 'js/nouislider.min.js' %}"></script>
		<script src="{% static 'js/jquery.zoom.min.js' %}"></script>
		<script src="{% static 'js/main.js' %}"></script>
		<script src="{% static 'js/reviews.js' %}"></script>
		<script src="{% static 'js/ajax.functions.js' %}"></script>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	</body>
</html>